SELECT [Date]
      ,[Pct_On_Site]
      ,[PctOnSite_seqlag-1]
      ,[PctOnSite_seqlag-2]
      ,[PctOnSite_seqlag-3]
      ,[PctOnSite_seqlag-4]
      --,[PctOnSite_seqlag-5]
      --,[PctOnSite_seqlag-6]
      --,[PctOnSite_seqlag-7]
      --,[PctOnSite_seqlag-8]
      --,[PctOnSite_seqlag-9]
      --,[PctOnSite_seqlag-10]
      --,[PctOnSite_seqlag-11]
      --,[PctOnSite_seqlag-12]
      --,[PctOnSite_seqlag-13]
      --,[PctOnSite_seqlag-14]
      --,[PctOnSite_seqlag-15]
      --,[PctOnSite_seqlag-16]
      --,[PctOnSite_seqlag-17]
      --,[PctOnSite_seqlag-18]
      --,[PctOnSite_seqlag-19]
      --,[PctOnSite_seqlag-20]
      ,[PctOnSite_SameDaylag-1]
      ,[PctOnSite_SameDaylag-2]
      ,[PctOnSite_SameDaylag-3]
      ,[PctOnSite_SameDaylag-4]
    --   ,[PctOnSite_SameDaylag-5]
      -- ,[PctOnSite_SameDaylag-6]
      -- ,[PctOnSite_SameDaylag-7]
      ,[PctOnSite_ma3]
    --   ,[PctOnSite_ma4]
    --   ,[PctOnSite_ma5]
    --   ,[PctOnSite_ma6]
    --   ,[PctOnSite_ma7]
    --   ,[PctOnSite_ma8]
      --,[PctOnSite_ma9]
      --,[PctOnSite_ma10]
      ,[PctOnSite_diff-1]
      ,[PctOnSite_diff-2]
      ,[PctOnSite_diff-3]
    --   ,[PctOnSite_diff-4]
    --   ,[PctOnSite_diff-5]
    --   ,[PctOnSite_diff-6]
    --   ,[PctOnSite_diff-7]

  FROM [Silver].[Moving_Averages_By_Day]
  ORDER BY 1